agent {
 data_dir = "/opt/spire/data"
 log_level = "INFO"
 server_address = "10.8.102.52"
 server_port = "8081"
 trust_domain = "pmbu.demo"
 trust_bundle_path = "/opt/spire/bootstrap/bundle.pem"
 socket_path = "/tmp/spire-agent/public/api.sock"
}
plugins {
 NodeAttestor "join_token" { plugin_data {} }
 KeyManager "disk" { plugin_data { directory = "/opt/spire/data" } }
 WorkloadAttestor "unix" { plugin_data {} }
}
